# CAPS FICHAS #5, #6, #7, #8 e #9
version: '3.3'
services:
  datasusftp:
    container_name: datasus-etl
    volumes:
      - '../scripts:/app/scripts'
      - '../data:/data'
    environment:
      - SCRIPT_NAME=transform_caps.py
    image: gleytonlima/datasusftp