# FICHA #14 e #15
version: '3.3'
services:
  datasusftp:
    container_name: datasus-etl
    volumes:
      - '../scripts:/app/scripts'
      - '../data:/data'
    environment:
      - SCRIPT_NAME=transform_cnes_sr_ua.py
    image: gleytonlima/datasusftp