# FICHA #16
version: '3.3'
services:
  datasusftp:
    container_name: datasus-etl
    volumes:
      - '../scripts:/app/scripts'
      - '../data:/data'
    environment:
      - SCRIPT_NAME=transform_sim_do.py
    image: gleytonlima/datasusftp