name: Gerar arquivo SIA-PA

on:
  workflow_dispatch:
    inputs:
      ano_mes:
        description: "Ano e mês no formato YYYY-MM. Exemplo 2023-01"
        required: false
      uf:
        description: "UF para o qual o arquivo vai ser gerado. Exemplo AM, DF. Obrigatório se ano_mes informado."
        required: false
  schedule:
    - cron: "0 0 28 * *"
env:
  NOME_BASE_ARQUIVO_DEFAULT: "SIA-PA.parquet"
  UF_DEFAULT: "DF"

jobs:
  extrair-transformar-enviar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar ambiente R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Configurando dependencias
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 2 # altere para desabilitar o cache caso hajam novas libs

      - name: Definir valores computados para ano_mes e uf, argumentos para o script (execução manual)
        if: github.event.inputs.ano_mes != ''
        run: |
          echo "ANO_MES_COMPUTADO=${{github.event.inputs.ano_mes}}" >> $GITHUB_ENV
          echo "UF_COMPUTADO=${{github.event.inputs.uf}}" >> $GITHUB_ENV

      - name: Definir valores computados para ano_mes e uf, argumentos para o script (valores default)
        if: github.event.inputs.ano_mes == ''
        run: |
          echo "ANO_MES_COMPUTADO=$(date -d "2 months ago" +'%Y-%m')" >> $GITHUB_ENV
          echo "UF_COMPUTADO=${{ env.UF_DEFAULT }}" >> $GITHUB_ENV

      - name: Definir nome final do arquivo
        run: |
          echo "NOME_ARQUIVO_COMPUTADO=${{ env.ANO_MES_COMPUTADO }}-${{ env.UF_COMPUTADO }}-${{ env.NOME_BASE_ARQUIVO_DEFAULT }}" >> $GITHUB_ENV

      - name: Executar script R
        run: Rscript extrair-transformar-enviar-siasus.R ${{ env.ANO_MES_COMPUTADO }} ${{ env.UF_COMPUTADO }}

      - name: Salvar arquivo como artefato
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.NOME_ARQUIVO_COMPUTADO }}
          path: ${{ env.NOME_ARQUIVO_COMPUTADO }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI Enviar para o data lake
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            chmod +x $GITHUB_WORKSPACE/upload_file.sh
            $GITHUB_WORKSPACE/upload_file.sh \
            ${{ secrets.ACCOUNT_NAME }} \
            ${{ secrets.ACCOUNT_KEY }} \
            ${{ secrets.CONTAINER_NAME }} \
            ${{ env.NOME_ARQUIVO_COMPUTADO }} \
            sia-pa/${{ env.NOME_ARQUIVO_COMPUTADO }}
